version: 2.1
orbs: 
  jq: circleci/jq@2.2.0
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run :
          name: create firebase rc
          command: |
             echo "$(jq -n '{"projects": {"default": $ID}}' --arg ID ${FIREBASE_PROJECTS})" > .firebaserc
             ls -al