version: 2.1
orbs: 
  jq: circleci/jq@2.2.0
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install
      - run:
          name: unit test
          command: |
            npm run test
      - run:
          name: build
          command: |
            npm run build
      - run :
          name: create firebase rc
          command: |
             echo "$(jq -n '{"projects": {"default": $ID}}' --arg ID ${FIREBASE_PROJECTS})" > .firebaserc
      - run :
          name: deploy to firebase
          command: |
             firebase deploy --only hosting --token ${FIREBASE_TOKEN}
             