version: 2.0
jobs:
  build:
    docker:
      - image: node:14.9.0-alpine
    steps:
      - checkout
      - run: |
          # build client
          npm run install && npm run build
          # TODO: add options for dev and prod
          # deploy client
          npm install -g firebase-tools && firebase deploy --only hosting --token ${FIREBASE_TOKEN}
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master